config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'

  resources :videos, except: :destroy do
    member do
      get :thumbnail_state, controller: 'progress'
      get :file_state, controller: 'progress'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :file, VideoFileUploader
  mount_uploader :thumbnail, ThumbnailUploader

  delegate :height, :width, to: :movie

  validates :file, :watermark_text, presence: true

  state_machine initial: :pending do
    event :process do
      transition [:pending, :processed] => :processing
    end

    event :complete do
      transition processing: :processed
    end
  end

  def movie
    path = file.current_path
    return nil unless path
    FFMPEG::Movie.new(path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/progress_controller.rb
class ProgressController < ApplicationController
  include ActionController::Live

  before_action :load_video, only: [:file_state, :thumbnail_state]

  def file_state
    sse_action do |sse|
      sse.write(@video.state)
    end
  end

  def thumbnail_state
    sse_action(retry: 1_000) do |sse|
      sse.write(@video.thumbnail.url)
    end
  end

  private

  def load_video
    @video = Video.find(params[:id])
  end

  def sse_action(options = {})
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream, options)
    yield sse
  ensure
    sse.close
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :load_video, only: [:show, :edit, :update]

  def index
    @videos = Video.order(created_at: :desc)
                   .page(params[:page])
                   .per(10)
                   .without_count
  end

  def new
    @video = Video.new
  end

  def create
    service = Services::Video::Create.new(create_params)
    if service.call
      flash[:notice] = I18n.t('videos.create.notice')
      redirect_to action: :index
    else
      @video = service.video
      flash[:error] = @video.errors.full_messages
      render action: :new
    end
  end

  def edit; end

  def update
    service = Services::Video::Update.new(update_params, @video)
    if service.call
      flash[:notice] = I18n.t('videos.update.notice')
      redirect_to action: :index
    else
      # TODO: do not raise
      @video = service.video
      flash[:error] = @video.errors.full_messages
      render action: :edit
      # raise
    end
  end

  private

  def load_video
    @video = Video.with_state(:processed).find(params[:id])
  end

  def create_params
    params.require(:video).permit(:file, :watermark_text)
  end

  def update_params
    params.require(:video).permit(:watermark_text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def duration(video)
    Time.at(video.duration).utc.strftime('%H:%M:%S')
  end

  def filename(video)
    video.file.file.filename
  end

  def thumbnail_url(video)
    video.thumbnail.url
  end
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'WaterVideo'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application'

    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{type: 'button', 'data-toggle': 'collapse', 'data-target': '.navbar-responsive-collapse'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'WaterVideo', root_path, class: 'navbar-brand'

    .container
      .row
        .col-xs-12
          = bootstrap_flash
          = yield

app/views/videos/_form.html.haml
= form_for @video do |f|
  .row
    .col-xs-12.col-md-8.col-md-offset-2
      .panel.panel-default
        .panel-heading
        .panel-body
          .row.bottom_10
            .col-xs-12
              = label(:video, :watermark_text)
              = f.text_field :watermark_text, class: 'form-control'

          - if @video.new_record?
            .row
              .col-xs-12
                %label.btn.btn-default.btn-block
                  = t('.choose')
                  = f.file_field :file, class: 'hidden', accept: 'video/*'

  .text-center
    = f.submit class: 'btn-success btn-lg'

app/views/videos/_thumbnail.html.haml
.thumbnail{'data-id': video.id, 'data-state': video.state }
  %img{src: thumbnail_url(video)}
  .caption
    %h5= filename(video)
    .bottom_10.clearfix
      .pull-left= duration(video)
      .pull-right= number_to_human_size(video.size)

    .processed{class: video.processed? ? '' : 'collapse' }
      = link_to video_path(video), class: 'btn btn-default' do
        = t('helpers.links.show')
        = glyph 'play-circle'

      = link_to edit_video_path(video), class: 'btn btn-default' do
        = t('helpers.links.edit')
        = glyph 'pencil'

    .pending{class: video.processed? ? 'collapse' : '' }
      .alert.alert-warning.bottom_0{style: 'padding:6px'}= t('.status', state: video.state)

app/views/videos/edit.html.haml
.page-header
  %h1.clearfix
    .pull-left= t('helpers.titles.edit', model: 'video')
    .pull-right
      = link_to videos_path, class: 'btn btn-default' do
        = t('helpers.links.cancel')
        = glyph 'remove-circle'

.page-content
  = render 'videos/form'

app/views/videos/index.html.haml
.page-header
  %h1.clearfix
    .pull-left= t('.title')
    .pull-right
      = link_to new_video_path, class: 'btn btn-default' do
        = t('.add')
        = glyph 'plus-sign'

.page-content
  .row
    - @videos.each do |video|
      .col-xs-12.col-sm-6.col-md-4
        = render 'videos/thumbnail', video: video

  .row.text-center
    %nav
      %ul.pager
        %li
          = link_to_prev_page @videos, t('.prev')
          = link_to_next_page @videos, t('.next')

app/views/videos/new.html.haml
.page-header
  %h1.clearfix
    .pull-left= t('helpers.titles.new', model: 'video')
    .pull-right
      = link_to videos_path, class: 'btn btn-default' do
        = t('helpers.links.cancel')
        = glyph 'remove-circle'

.page-content
  = render 'videos/form'

app/views/videos/show.html.haml
.embed-responsive.embed-responsive-16by9
  %video.embed-responsive-item{autoplay: '', controls: ''}
    %source{src: @video.file.watermark.url, type: 'video/mp4'}